In [20]:
from nba_py import player
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

Try to use an RNN to characterize player progression, identify the peak of a players career, MVP predictions, etc.

In [21]:
def get_PID(first_name,last_name):
    """Obtains the player ID number of the desired player.
    
    Parameters
    -----------
    
    first_name: str
        First name of player
    last_name: str
        Last name of player
    
    Returns
    -------
    
    ID : float
        The player's ID number. 
    """
    
    playa = player.get_player(first_name=first_name,last_name=last_name)
    
    return playa.values[0]

In [22]:
mj = get_PID('Michael','Jordan')
lbj = get_PID('Lebron','James')

MJ = player.PlayerCareer(player_id=mj)
LBJ = player.PlayerCareer(player_id=lbj)

In [43]:
LBJPPS =player.PlayerVsPlayer

In [ ]:
LBJPPS =player.PlayerVsPlayer

In [42]:
LBJPPS.overall()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Overall,2017-18,82,50,32,0.61,36.9,10.5,19.3,0.542,1.8,5.0,0.367,4.7,6.5,0.731,1.2,7.5,8.6,9.1,4.2,1.4,0.9,0.8,1.7,5.4,27.5,1.3,54.1,52,18,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,266,2017-18

In [29]:
MJ.regular_season_career_totals()

,PLAYER_ID,LEAGUE_ID,Team_ID,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,893,00,0,1072,1039,38.3,11.4,22.9,0.497,0.5,1.7,0.327,6.8,8.2,0.835,1.6,4.7,6.2,5.3,2.3,0.8,2.7,2.6,30.1

In [30]:
LBJ.regular_season_career_totals()

,PLAYER_ID,LEAGUE_ID,Team_ID,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,00,0,1143,1142,38.8,9.9,19.6,0.504,1.4,4.1,0.344,6.0,8.1,0.739,1.2,6.1,7.4,7.2,1.6,0.8,3.5,1.8,27.2

In [25]:
LBJ.regular_season_totals()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,39.5,7.9,18.9,0.417,0.8,2.7,0.290,4.4,5.8,0.754,1.3,4.2,5.5,5.9,1.6,0.7,3.5,1.9,20.9
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,42.3,9.9,21.1,0.472,1.4,3.9,0.351,6.0,8.0,0.750,1.4,6.0,7.4,7.2,2.2,0.7,3.3,1.8,27.2
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,42.5,11.1,23.1,0.480,1.6,4.8,0.335,7.6,10.3,0.738,0.9,6.1,7.0,6.6,1.6,0.8,3.3,2.3,31.4
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,40.9,9.9,20.8,0.476,1.3,4.0,0.319,6.3,9.0,0.698,1.1,5.7,6.7,6.0,1.6,0.7,3.2,2.2,27.3
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,40.4,10.6,21.9,0.484,1.5,4.8,0.315,7.3,10.3,0.712,1.8,6.1,7.9,7.2,1.8,1.1,3.4,2.2,30.0
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,37.7,9.7,19.9,0.489,1.6,4.7,0.344,7.3,9.4,0.780,1.3,6.3,7.6,7.2,1.7,1.1,3.0,1.7,28.4
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,39.0,10.1,20.1,0.503,1.7,5.1,0.333,7.8,10.2,0.767,0.9,6.4,7.3,8.6,1.6,1.0,3.4,1.6,29.7
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,38.8,9.6,18.8,0.510,1.2,3.5,0.330,6.4,8.4,0.759,1.0,6.5,7.5,7.0,1.6,0.6,3.6,2.1,26.7
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,37.5,10.0,18.9,0.531,0.9,2.4,0.362,6.2,8.1,0.771,1.5,6.4,7.9,6.2,1.9,0.8,3.4,1.5,27.1
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,37.9,10.1,17.8,0.565,1.4,3.3,0.406,5.3,7.0,0.753,1.3,6.8,8.0,7.3,1.7,0.9,3.0,1.4,26.8
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,37.7,10.0,17.6,0.567,1.5,4.0,0.379,5.7,7.6,0.750,1.1,5.9,6.9,6.3,1.6,0.3,3.5,1.6,27.1
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,36.1,9.0,18.5,0.488,1.7,4.9,0.354,5.4,7.7,0.710,0.7,5.3,6.0,7.4,1.6,0.7,3.9,2.0,25.3
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,35.6,9.7,18.6,0.520,1.1,3.7,0.309,4.7,6.5,0.731,1.5,6.0,7.4,6.8,1.4,0.6,3.3,1.9,25.3
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,37.8,9.9,18.2,0.548,1.7,4.6,0.363,4.8,7.2,0.674,1.3,7.3,8.6,8.7,1.2,0.6,4.1,1.8,26.4
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,36.9,10.5,19.3,0.542,1.8,5.0,0.367,4.7,6.5,0.731,1.2,7.5,8.6,9.1,1.4,0.9,4.2,1.7,27.5

In [ ]:
    playa = player.get_player(first_name=first_name,last_name=last_name)

In [6]:
player.get_player(first_name='Joel',last_name='Embiid')

1083    203954
Name: PERSON_ID, dtype: int64

In [15]:
lebron = player.PlayerCareer(player_id=2544)

In [16]:
lebron.post_season_career_totals()

,PLAYER_ID,LEAGUE_ID,Team_ID,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,00,0,227,227,42.0,10.2,20.8,0.488,1.5,...,0.743,1.5,7.3,8.9,6.9,1.8,1.0,3.5,2.4,28.7

In [32]:
lbjD = player.PlayerDefenseTracking(player_id=2544,last_n_games=3)

In [33]:
lbjD.overall()

,CLOSE_DEF_PERSON_ID,GP,G,DEFENSE_CATEGORY,FREQ,D_FGM,D_FGA,D_FG_PCT,NORMAL_FG_PCT,PCT_PLUSMINUS
0,2544,3,3,Overall,1.00,4.67,8.33,0.560,0.473,0.087
1,2544,3,3,3 Pointers,0.44,1.33,3.67,0.364,0.386,-0.023
2,2544,3,3,2 Pointers,0.56,3.33,4.67,0.714,0.518,0.196
3,2544,3,2,Less Than 6 Ft,0.20,1.33,1.67,0.800,0.633,0.167
4,2544,3,3,Less Than 10 Ft,0.28,1.67,2.33,0.714,0.566,0.148
5,2544,3,3,Greater Than 15 Ft,0.68,2.67,5.67,0.471,0.414,0.057

In [7]:
embiid = 203954

In [26]:
embiidD = player.PlayerDefenseTracking(player_id=embiid,last_n_games=11)

In [27]:
embiidD.overall()

,CLOSE_DEF_PERSON_ID,GP,G,DEFENSE_CATEGORY,FREQ,D_FGM,D_FGA,D_FG_PCT,NORMAL_FG_PCT,PCT_PLUSMINUS
0,203954,3,3,Overall,1.000,4.00,13.00,0.308,0.504,-0.197
1,203954,3,2,3 Pointers,0.179,0.67,2.33,0.286,0.397,-0.111
2,203954,3,3,2 Pointers,0.821,3.33,10.67,0.313,0.539,-0.227
3,203954,3,3,Less Than 6 Ft,0.462,2.00,6.00,0.333,0.631,-0.298
4,203954,3,3,Less Than 10 Ft,0.564,2.33,7.33,0.318,0.580,-0.262
5,203954,3,3,Greater Than 15 Ft,0.385,1.00,5.00,0.200,0.392,-0.192